global:
  dashboard:
    path: "admin"
    page:
      templatePath: "template/dashboard.ts"
    layout:
      templatePath: "template/layout.ts"
  prismaConfig:
    templatePath: "template/prismaLib.ts"
components:
  sidebar:
    templatePath: "template/sidebar.ts"
  crud:
    readList:
      templatePath: "template/crud/readList.ts"

#  ui:
#    input:
#      templatePath: "template/components/input.ts"
entity:
  hidden:
    disable: true
  user:
    disable: false
#    ignore:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
#    enable:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
#  test:
#    path: heyyy
