global:
  dashboard:
    path: "admin"
    page:
      templatePath: "template/dashboard.ts"
    layout:
      templatePath: "template/layout.ts"
  prismaConfig:
    templatePath: "template/prismaLib.ts"
#components:
#  ui:
#    input:
#      templatePath: "template/components/input.ts"
#entity:
#  user:
#    ignore:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
#  test:
#    path: heyyy
