global:
  dashboard:
    path: "admin"
    page:
      templatePath: "template/dashboard.tsx"


entity:
#  user:
#    ignore:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
  test:
    path: heyyy
