global:
  dashboard:
    path: "admin"
#    page:
#      templatePath: "template/dashboard"


entity:
#  user:
#    ignore:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
  test:
    path: heyyy
