global:
  dashboard:
    path: "admin"
    page:
      templatePath: "template/dashboard.ts"
    layout:
      templatePath: "template/layout.ts"
  prismaConfig:
    templatePath: "template/prismaLib.ts"
components:
  sidebar:
    templatePath: "template/sidebar.ts"
  crud:
    actions:
      path: "actions/gen"
      templatePath: "template/crud/actions.ts"
    readList:
      page:
        templatePath: "template/crud/readList.ts"

#  ui:
#    input:
#      templatePath: "template/components/input.ts"
entity:
  hidden:
    disable: true
  user:
    disable: false
  hey:
    components:
      actions:
        path: "app/admin/heys"
        templatePath: "template/entity/hey/actions.ts"
      readList:
        page:
          templatePath: "template/entity/hey/readList.ts"
#    ignore:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
#    enable:
#      - readList
#      - readOne
#      - delete
#      - create
#      - update
#  test:
#    path: heyyy
